FROM tomcat:alpine

MAINTAINER Joan Codina <joan.codina@upf.edu>

COPY target/author-profiling-demo-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/author-profiling-demo.war
COPY CoNLL2009-ST-English-ALL.anna-3.3.lemmatizer.model /home/CoNLL2009-ST-English-ALL.anna-3.3.lemmatizer.model



EXPOSE 8080
